services:
  - type: web
    name: backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://luislinnovel:OUWW8RUFiAo0RPup@cluster0.nr3hfws.mongodb.net/products?retryWrites=true&w=majority&appName=Cluster0
      - key: PORT
        value: 5000
    autoDeploy: true

  - type: web
    name: frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    autoDeploy: true
